# -*- coding: utf-8 -*-
"""example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrmO7cWSo4SzSS2UwRs_qncEh61GUhp6
"""

!pip install streamlit

import streamlit as st

st.title("Test Streamlit App")
st.write("Hello, World!")

